# Generated by Django 3.1.7 on 2021-03-25 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articlee',
            new_name='Article',
        ),
    ]
